import Head from 'next/head'
import { Header, PostCard, PostWidget, Categories } from '@/components/index'
import { getPosts } from '@/lib/api'

export async function getStaticProps() {
  const posts = (await getPosts()) || []

  return {
    props: { posts },
  }
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className='container mx-auto px-5 md:px-10 mb-8'>
        <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
          <div className='col-span-1 lg:col-span-8 bg-blue-600'>
            {posts.map((post) => (
              <PostCard key={post.title} post={post} />
            ))}
          </div>
          <div className='col-span-1 lg:col-span-4 bg-gray-600'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </>
  )
}
