import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header'
import PostCard from '@/components/PostCard'
import PostWidget from '@/components/PostWidget'
import Categories from '@/components/Categories'
import styles from '@/styles/Home.module.css'

const posts = [
  { title: 'Best NPM Packages', excerpt: 'Learn NPM' },
  { title: 'Why should you use Yarn', excerpt: 'Learn Yarn' },
]

export default function Home() {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Header />
        <div className='container mx-auto px-10 mb-8'>
          <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
            <div className='col-span-1 lg:col-span-8 bg-blue-600'>
              {posts.map((post) => (
                <PostCard key={post.title} post={post}/>
              ))}
            </div>
            <div className='col-span-1 lg:col-span-4 bg-gray-600'>
              <PostWidget />
              <Categories />
            </div>
          </div>
        </div>
      </>
  )
}
